name: Code checks flake8 and mypy

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: alexanderdamiani/pylinter@v1.3.0
      with:
        python-version: ${{ matrix.python-version }}
        flake8-flags: '--count --show-source --statistics'
        mypy-flags: '--ignore-missing-imports'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
